### ISSUE TITLE
Getting error on vinli app set-current

### ISSUE THREAD

**Issue by sandro-csimas** [vinli/vinli-cli#9]
When I execute this command:
````
vinli app set-current --app <APP_NAME>
````
The following error is happening:
````
Developer Account:email: <DEV_EMAIL>
Developer Account:password: ************
Signing in to <DEV_EMAIL> developer account...
Authenticated user
        Cannot read property 'item' of undefined
````
````
Cannot read property 'item' of undefined
````

**Comment by shayneo** [comment]
@sandro-csimas are you still seeing this issue? I'm wondering if this was happening because of there being no apps registered to the dev account.

**Comment by sandro-csimas** [comment]
@shayneo, this problem happened because my app was in another dev account. Now its working.
